services:
  api:
    build:
      context: .
      dockerfile: Enpal.HomeChallenge.Api/Dockerfile
    ports:
        - "3000:8080"
    environment:
      ConnectionStrings__DbConnectionString: "Host=db;Port=5432;Database=coding-challenge;Username=postgres;Password=mypassword123!;"
  
  db:
    build:
        context: ./Enpal.HomeChallenge.Infrastructure/Data/Database
        dockerfile: Dockerfile
    ports:
        - "5432:5432"